### ISSUE TITLE
Have explicit support for getting the position at the end of the document.

### ISSUE THREAD

**Issue by bolinfest** [GiveMe-A-Name/lsp-textdocument#3]
This is how I do this today, but it feels a little weird:

```rust
// TextDocument::content_len() is a private method, but position_at()
// appears to clamp the offset argument internally at self.content_len(),
// so we just pass usize::MAX as the offset.
let last_position = document.position_at(u32::MAX);
let code_after = document
    .get_content(Some(Range {
        start: *position,
        end: last_position,
    }))
    .to_owned();
```

Maybe `TextDocument` should have a `pub fn last_position()` or something (or maybe just make `content_len()` public)? I don't have strong feelings either way.

**Comment by GiveMe-A-Name** [comment]
Yes, we can export more methods that developer can get more information from document.

**Comment by GiveMe-A-Name** [comment]
I export the `content_len` and the `line_count` to make developer get more information from document. 

More detail: https://crates.io/crates/lsp-textdocument/0.2.1
